<br>

## **Convert from dataframe to tensor**

<br>

## **Method 1**

In [1]:
import pandas as pd

In [2]:
df_dataframe = pd.DataFrame({'col_X1': [1,2,3,4,5],
                             'col_X2': [2,4,6,8,10],
                             'col_y': [10,20,30,40,50]})

In [3]:
df_dataframe

col_X1  col_X2  col_y
0       1       2     10
1       2       4     20
2       3       6     30
3       4       8     40
4       5      10     50

In [4]:
type(df_dataframe)

pandas.core.frame.DataFrame

In [5]:
import torch

In [6]:
X = torch.tensor(df_dataframe[['col_X1','col_X2']])

ValueError: could not determine the shape of object type 'DataFrame'

**Error will be encountered. See below or Method 2**

<br>

In [7]:
df_array_X = df_dataframe[['col_X1','col_X2']].to_numpy(dtype='float32')

In [8]:
df_array_X

array([[ 1.,  2.],
       [ 2.,  4.],
       [ 3.,  6.],
       [ 4.,  8.],
       [ 5., 10.]], dtype=float32)

In [9]:
df_array_y = df_dataframe[['col_y']].to_numpy(dtype='float32')

In [10]:
df_array_y

array([[10.],
       [20.],
       [30.],
       [40.],
       [50.]], dtype=float32)

In [11]:
X = torch.tensor(df_array_X)

In [12]:
X

tensor([[ 1.,  2.],
        [ 2.,  4.],
        [ 3.,  6.],
        [ 4.,  8.],
        [ 5., 10.]])

In [13]:
type(X)

torch.Tensor

In [14]:
X.dtype

torch.float32

In [15]:
y = torch.tensor(df_array_y)

In [16]:
y

tensor([[10.],
        [20.],
        [30.],
        [40.],
        [50.]])

In [17]:
type(y)

torch.Tensor

In [18]:
y.dtype

torch.float32

<br>

## **Method 2**

In [19]:
import pandas as pd

In [20]:
df_dataframe = pd.DataFrame({'col_X1': [1,2,3,4,5],
                             'col_X2': [2,4,6,8,10],
                             'col_y': [10,20,30,40,50]})

In [21]:
df_dataframe

col_X1  col_X2  col_y
0       1       2     10
1       2       4     20
2       3       6     30
3       4       8     40
4       5      10     50

In [22]:
type(df_dataframe)

pandas.core.frame.DataFrame

In [23]:
import torch

In [24]:
X = torch.tensor(df_dataframe[['col_X1','col_X2']].values).float()

In [25]:
X

tensor([[ 1.,  2.],
        [ 2.,  4.],
        [ 3.,  6.],
        [ 4.,  8.],
        [ 5., 10.]])

In [26]:
type(X)

torch.Tensor

In [27]:
X.dtype

torch.float32

In [28]:
y = torch.tensor(df_dataframe[['col_y']].values).float()

In [29]:
y

tensor([[10.],
        [20.],
        [30.],
        [40.],
        [50.]])

In [30]:
type(y)

torch.Tensor

In [31]:
y.dtype

torch.float32