In [1]:
from torchvision import transforms
import torch.nn as nn
import torch
import numpy as np

In [2]:
torch.manual_seed(2)

In [3]:
image = np.array([[[1,1,1],
                   [1,0,1],
                   [1,1,1]],
                  [[1,1,1],
                   [1,0,1],
                   [1,1,1]],
                  [[1,1,1],
                   [1,0,1],
                   [1,1,1]]], dtype='float32')

In [4]:
# see MS Excel file column B to column F

to_tensor = transforms.ToTensor()
image_tensor = to_tensor(image)
image_tensor

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 0., 1.],
         [1., 0., 1.],
         [1., 0., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [5]:
conv2d_1 = nn.Conv2d(in_channels=3, out_channels=1, kernel_size=(2,2), padding=1)

In [6]:
# see MS Excel file column R to column U

output_1 = conv2d_1(image_tensor)
output_1

tensor([[[-0.2924,  0.0249, -0.1753,  0.0204],
         [-0.5480, -0.0439, -0.2987,  0.2759],
         [-0.5480, -0.0439, -0.2987,  0.2759],
         [-0.3190, -0.1323, -0.1869,  0.1920]]], grad_fn=<SqueezeBackward1>)

In [7]:
# see MS Excel file column H to column I

conv2d_1.weight.data

tensor([[[[ 0.0662, -0.0687],
          [ 0.0792, -0.0147]],

         [[ 0.1233,  0.0687],
          [-0.0332, -0.2334]],

         [[ 0.0659, -0.2556],
          [ 0.0379,  0.0192]]]])

In [8]:
# see MS Excel file column P

conv2d_1.bias.data

tensor([-0.0635])

In [9]:
relu_1 = nn.ReLU()

In [10]:
# see MS Excel file column W to column Z

output_2 = relu_1(output_1)
output_2

tensor([[[0.0000, 0.0249, 0.0000, 0.0204],
         [0.0000, 0.0000, 0.0000, 0.2759],
         [0.0000, 0.0000, 0.0000, 0.2759],
         [0.0000, 0.0000, 0.0000, 0.1920]]], grad_fn=<ReluBackward0>)