In [1]:
from torchvision import transforms
import torch.nn as nn
import torch
import numpy as np

In [2]:
torch.manual_seed(2)

In [3]:
image = np.array([[[1,1,1],
                   [1,0,1],
                   [1,1,1]],
                  [[1,1,1],
                   [1,0,1],
                   [1,1,1]],
                  [[1,1,1],
                   [1,0,1],
                   [1,1,1]]], dtype='float32')

In [4]:
# see MS Excel file column B to column F Sheet1 and Sheet2

to_tensor = transforms.ToTensor()
image_tensor = to_tensor(image)
image_tensor

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 0., 1.],
         [1., 0., 1.],
         [1., 0., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [5]:
conv2d_1 = nn.Conv2d(in_channels=3, out_channels=2, kernel_size=(2,2), padding=1)

In [6]:
# see MS Excel file column R to column U Sheet1 and Sheet2

with torch.no_grad():
    output_1 = conv2d_1(image_tensor)
output_1

tensor([[[-0.2564,  0.0609, -0.1393,  0.0565],
         [-0.5119, -0.0079, -0.2627,  0.3119],
         [-0.5119, -0.0079, -0.2627,  0.3119],
         [-0.2830, -0.0963, -0.1509,  0.2280]],

        [[ 0.6781,  0.2859,  0.6745, -0.0386],
         [ 0.7242,  0.2783,  0.3744, -0.2626],
         [ 0.7242,  0.2783,  0.3744, -0.2626],
         [ 0.1222,  0.0684, -0.2241, -0.1481]]])

In [7]:
# see MS Excel file column H to column I Sheet1 and Sheet2

conv2d_1.weight.data

tensor([[[[ 0.0662, -0.0687],
          [ 0.0792, -0.0147]],

         [[ 0.1233,  0.0687],
          [-0.0332, -0.2334]],

         [[ 0.0659, -0.2556],
          [ 0.0379,  0.0192]]],


        [[[-0.0635,  0.2360],
          [ 0.0193,  0.1197]],

         [[ 0.1222, -0.1703],
          [-0.1110,  0.2776]],

         [[-0.2828, -0.0196],
          [-0.0229,  0.2048]]]])

In [8]:
# see MS Excel file column P Sheet1 and Sheet2

conv2d_1.bias.data

tensor([-0.0274,  0.0760])

In [9]:
relu_1 = nn.ReLU()

In [10]:
# see MS Excel file column W to column Z Sheet1 and Sheet2

with torch.no_grad():
    output_2 = relu_1(output_1)
output_2

tensor([[[0.0000, 0.0609, 0.0000, 0.0565],
         [0.0000, 0.0000, 0.0000, 0.3119],
         [0.0000, 0.0000, 0.0000, 0.3119],
         [0.0000, 0.0000, 0.0000, 0.2280]],

        [[0.6781, 0.2859, 0.6745, 0.0000],
         [0.7242, 0.2783, 0.3744, 0.0000],
         [0.7242, 0.2783, 0.3744, 0.0000],
         [0.1222, 0.0684, 0.0000, 0.0000]]])